<?php

class Auto extends Models{
    
    public $id = 0;
    public $model;
    public $year;
    public $engine;
    public $color;
    public $kpp;
    public $speed;
    public $price;

    public function getTableName(){
        return "auto";
    }
    
    public static function model($className = __CLASS__){
        return parent::model($className);
    }

    public function findAll($params = [], $orders = [])
    {
        $listAuto = parent::findAll($params, $orders); // TODO: Change the autogenerated stub
        foreach ($listAuto as $key=>$value){
            $model = AutoModels::model()->find($value['model'], true);
            $listAuto[$key]['modelName'] = $model["name"];
        }
        return $listAuto;
    }

    public function getList()
    {
        $listAuto = parent::findAll();
        $result = [];
        foreach ($listAuto as $key=>$value){
            $model = AutoModels::model()->find($value['model'], true);
            $result[] = [
                'id' => $value['id'],
                'marka' => "", //$value['marka'],
                'modelName' => $model["name"],
            ];
        }
        return $result;
    }

}
